// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xychfxpebhijimqpemuz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5Y2hmeHBlYmhpamltcXBlbXV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMDgyODEsImV4cCI6MjA2MDg4NDI4MX0.nRJEYWjiBWydTsKXgLxneUgdLj-1TO4gBVIicPFWlKk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);